### PR TITLE
Removed ign_ros2_control from dependencies.repos

### PR DESCRIPTION
**Pull request by ahcorde**
Signed-off-by: ahcorde <ahcorde@gmail.com>

`ign_ros2_control` is released in Galactic, this should be installed with the `rosdep` command

### CODE REVIEW

**Comment by ahcorde** [comment]
The error in the CI should be fixed with this other PR https://github.com/turtlebot/turtlebot4_simulator/pull/8

**Comment by roni-kreinin** [comment]
Getting this error when I try to run the sim:

```
[ign gazebo-1] [libprotobuf ERROR google/protobuf/descriptor_database.cc:58] File already exists in database: ignition/msgs/actor.proto
[ign gazebo-1] [libprotobuf FATAL google/protobuf/descriptor.cc:1358] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
[ign gazebo-1] terminate called after throwing an instance of 'google::protobuf::FatalException'
[ign gazebo-1]   what():  CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
[ign gazebo-1] Stack trace (most recent call last):
[ign gazebo-1] #31   Object "/usr/lib/x86_64-linux-gnu/ign-gazebo-5/plugins/libignition-gazebo-user-commands-system.so", at 0x7fb9bef9e3e9, in ignition::gazebo::v5::systems::CreateCommand::Execute()
[ign gazebo-1] #30   Object "/lib/x86_64-linux-gnu/libignition-gazebo5.so.5", at 0x7fb9e85cafb1, in ignition::gazebo::v5::SdfEntityCreator::CreateEntities(sdf::v11::Model const*)
[ign gazebo-1] #29   Object "/lib/x86_64-linux-gnu/libignition-gazebo5.so.5", at 0x7fb9e85dbc80, in void ignition::gazebo::v5::EventManager::Emit<ignition::common::EventT<void (unsigned long, std::shared_ptr<sdf::v11::Element>), ignition::gazebo::v5::events::LoadPluginsTag>
, unsigned long const&, std::shared_ptr<sdf::v11::Element> const&>(unsigned long const&, std::shared_ptr<sdf::v11::Element> const&)
[ign gazebo-1] #28   Object "/lib/x86_64-linux-gnu/libignition-gazebo5.so.5", at 0x7fb9e86067a9, in ignition::gazebo::v5::SimulationRunner::LoadPlugins(unsigned long, std::shared_ptr<sdf::v11::Element> const&)
[ign gazebo-1] #27   Object "/lib/x86_64-linux-gnu/libignition-gazebo5.so.5", at 0x7fb9e86056fb, in ignition::gazebo::v5::SimulationRunner::LoadPlugin(unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_
string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<sdf::v11::Element> const&)
[ign gazebo-1] #26   Object "/lib/x86_64-linux-gnu/libignition-gazebo5.so.5", at 0x7fb9e86166a8, in ignition::gazebo::v5::SystemLoader::LoadPlugin(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::c
har_traits<char>, std::allocator<char> > const&, std::shared_ptr<sdf::v11::Element> const&)
[ign gazebo-1] #25   Object "/lib/x86_64-linux-gnu/libignition-gazebo5.so.5", at 0x7fb9e8616fbc, in
[ign gazebo-1] #24   Object "/lib/x86_64-linux-gnu/libignition-plugin1-loader.so.1", at 0x7fb9e94eb670, in ignition::plugin::Loader::LoadLib(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
[ign gazebo-1] #23   Object "/lib/x86_64-linux-gnu/libignition-plugin1-loader.so.1", at 0x7fb9e94eaa7d, in ignition::plugin::Loader::Implementation::LoadLib(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
[ign gazebo-1] #22   Object "/lib/x86_64-linux-gnu/libdl.so.2", at 0x7fb9ed1723d9, in dlopen
[ign gazebo-1] #21   Object "/lib/x86_64-linux-gnu/libdl.so.2", at 0x7fb9ed172b58, in
[ign gazebo-1] #20   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fb9ed38a902, in _dl_catch_error
[ign gazebo-1] #19   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fb9ed38a837, in _dl_catch_exception
[ign gazebo-1] #18   Object "/lib/x86_64-linux-gnu/libdl.so.2", at 0x7fb9ed17234b, in
[ign gazebo-1] #17   Object "/lib64/ld-linux-x86-64.so.2", at 0x7fb9ed7ce5f9, in
[ign gazebo-1] #16   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fb9ed38a837, in _dl_catch_exception
[ign gazebo-1] #15   Object "/lib64/ld-linux-x86-64.so.2", at 0x7fb9ed7cf0be, in
[ign gazebo-1] #14   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fb9ed38a894, in _dl_catch_exception
[ign gazebo-1] #13   Object "/lib64/ld-linux-x86-64.so.2", at 0x7fb9ed7cac90, in
[ign gazebo-1] #12   Object "/lib64/ld-linux-x86-64.so.2", at 0x7fb9ed7cab89, in
[ign gazebo-1] #11   Object "/lib/x86_64-linux-gnu/libignition-msgs5.so.5", at 0x7fb9bd851768, in void std::call_once<void (&)()>(std::once_flag&, void (&)())
[ign gazebo-1] #10   Object "/lib/x86_64-linux-gnu/libpthread.so.0", at 0x7fb9ed21847e, in
[ign gazebo-1] #9    Object "/lib/x86_64-linux-gnu/libignition-msgs5.so.5", at 0x7fb9bd84c3ed, in protobuf_ignition_2fmsgs_2factor_2eproto::AddDescriptorsImpl()
[ign gazebo-1] #8    Object "/lib/x86_64-linux-gnu/libprotobuf.so.17", at 0x7fb9e79e387d, in
[ign gazebo-1] #7    Object "/lib/x86_64-linux-gnu/libgcc_s.so.1", at 0x7fb9e92c35a9, in _Unwind_Resume
[ign gazebo-1] #6    Object "/lib/x86_64-linux-gnu/libgcc_s.so.1", at 0x7fb9e92c2bee, in
[ign gazebo-1] #5    Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7fb9e9376d20, in __gxx_personality_v0
[ign gazebo-1] #4    Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7fb9e9376368, in
[ign gazebo-1] #3    Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7fb9e937738b, in
[ign gazebo-1] #2    Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7fb9e936b910, in
[ign gazebo-1] #1    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fb9ed24c858, in abort
[ign gazebo-1] #0    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fb9ed26d03b, in gsignal
[ign gazebo-1] Aborted (Signal sent by tkill() 427417 1935204418)
```

**Comment by ahcorde** [comment]
Do you have any other versions of ignition installed ? then it's linking to the wrong version.

**Comment by roni-kreinin** [comment]
I only have edifice installed. I ran the sim without issue using the `galactic` branch, then I switched to this branch, removed the source `ign_ros2_control` package and installed it with rosdep.

**Comment by ahcorde** [comment]
This line is still required in the README.md 

```
export IGNITION_VERSION=edifice
```

because `rosdep` is getting the packages from the `package.xml`. Can you check if there is `libignition-gazebo3` installed ? If so please remove it and try again.

**Comment by roni-kreinin** [comment]
If I remove `libignition-gazebo3` with `sudo apt remove libignition-gazebo3` then `ign_ros2_control` also gets removed. Similarly, if I install `ign_ros2_control` then `libignition-gazebo3` also gets installed even with `IGNITION_VERSION=edifice`.

**Comment by ahcorde** [comment]
ups, Looking in to it

**Comment by roni-kreinin** [comment]
@ahcorde I see that the issue has been fixed. Would it be possible to release the package to ros2-testing?

**Comment by ahcorde** [comment]
Once this PR is merged https://github.com/ros/rosdistro/pull/32477 , then you should wait some hours and the package should be available there

**Comment by roni-kreinin** [comment]
Can you add these instructions to the README right after the Ignition Edifice section?

### ROS2 Testing packages

Change your ROS2 package source to ros2-testing to get the latest updates.

- Edit `/etc/apt/sources.list.d/ros2.list`
- Change `http://packages.ros.org/ros2/ubuntu focal main` to `http://packages.ros.org/ros2-testing/ubuntu focal main`
- Run `sudo apt update`

**Pull request merged**
